Feature functionality
shadabwahidullah/Book-Store pull request #2
Opened 2021-11-09 22:41 UTC by shadabwahidullah

## In this milestone I have:

- added the functionality to add a new book
- added the functionality to remove a book

## Used Technologies:

- HTML
- JavaScript
- React
- Redux
- Linters

2021-11-10 01:00 UTC, omar-labana requested changes
Hi @shadabwahidullah, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_N/A_
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-10 01:00 UTC, omar-labana commented on src/components/InputBook.js
> +
- [x] According to the project requirements, this component should make use of the `useState` hook along with the `onChange` event listener on each input field. Now, you might ask yourself, why is such a requirement is necessary while it works fine as intended? one of the simple answers is since you can edit the `HTML` page using your dev tools, form validation, and input values might become obsolete(having falsy values since form validation is missed up), so another layer of validation should be added via Javascript to make sure the data submitted by the user is validated, to do so, the developer(you) attaches an event lister to your input, thus every time it changes you might execute a function that validates input values. You should only dispatch redux actions after getting the right validated data from the user, not just getting it from whatever value the user has entered.

2021-11-10 01:00 UTC, omar-labana commented on src/components/Book.js
> +    console.log('id is ', event.target.parentElement.key);
- [x] Kindly, remove unnecessary log statements from your code base.

2021-11-10 16:59 UTC, shadabwahidullah commented on src/components/InputBook.js
> +
Do you simply mean, I have to validate my form?

2021-11-10 18:07 UTC, ArthurGC approved these changes
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  @shadabwahidullah 

Amazing job using React Hook Form! 💯
Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 

![](https://media0.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-10 18:24 UTC, merged

2021-11-11 00:54 UTC, omar-labana commented on src/components/InputBook.js
> +
@shadabwahidullah You may use it to do so, sometimes you may notice real-time warnings when you are filing a form, this is done using the `onChange` event listener.

2021-11-11 00:56 UTC, omar-labana commented on src/components/InputBook.js
> +
sorry if my explanation was a bit unclear